### ISSUE TITLE
TODO suite à réunion du 18 février

### ISSUE THREAD

**Issue by BernardNotarianni** [Erlang-Startups-Paris/distributed-wordcount#1]
Les choses à faire avant le meetup
- [x] Mettre le repo git dans l’organisation « meetup »
- [ ] Refactorer le code pour utiliser « file :position »
- [ ] Parametrer le DHCP
- [ ] Formaliser une timeline/procédure pour dérouler la démo du meetup
